### ISSUE TITLE
Validator: Add DryType email validator

### ISSUE THREAD

**Issue by SwapnilSoni1999** [SwapnilSoni1999/express-dry#2]
- The project needs an email validator
- You can put your validator lib code in [validators](https://github.com/SwapnilSoni1999/express-dry/tree/main/validators)
- once done assign the type [over here](https://github.com/SwapnilSoni1999/express-dry/blob/main/types.js#L1)

**Important**
- Make sure you use `drytypes` method `.makeDryType` 
- Also a DryType needs a return object containing `{ status, message }` (message is optional for `status: true`)

**Comment by omeiirr** [comment]
Created a pull request [here](https://github.com/SwapnilSoni1999/express-dry/pull/3)

Review and let me know if any changes are required @SwapnilSoni1999

**Comment by SwapnilSoni1999** [comment]
Amazing <3

**Comment by omeiirr** [comment]
You're welcome ;)

(I suggest adding the 'Hacktoberfest' topic to this repository, you'll see much more traffic here :P)

Good luck with this project 💯

**Comment by SwapnilSoni1999** [comment]
> You're welcome ;)
> 
> (I suggest adding the 'Hacktoberfest' topic to this repository, you'll see much more traffic here :P)
> 
> Good luck with this project 100

Loads of thanks <3
